import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container:{
        borderWidth:1,
        flexDirection:'row',
        alignItems:'center',
        width:'35%',
        borderRadius:6,
        paddingVertical:7,
        paddingHorizontal:10,
        shadowColor:'#000'
    },
    search:{
        fontSize:10,
        fontFamily:'Montserrat-Regular',
        color:'#353535',
        marginLeft:10,
        marginBottom:5
    },
    view:{
        flexDirection:'row',
        justifyContent:'space-between',
        borderBottomWidth:.5,
        borderColor:'#dae1ed'
    },
    view1:{
        borderColor:'#0FAF33',
        borderWidth:1,
        height:18,
        width:18,
        alignItems:'center',
        justifyContent:'center',
        borderRadius:2
    },
    border:{
        height:10,
        width:10,backgroundColor:'#0FAF33',
        borderRadius:10
    },
    tag:{
        backgroundColor:'#EF3837',
        paddingVertical:2,
        paddingHorizontal:8,
        borderRadius:3,marginLeft:8
    },
    best:{
        color:'#fff',
        fontFamily:'Montserrat-Medium',
        fontSize:8
    },
    title:{
        fontFamily:"Montserrat-SemiBold",
        fontSize:15,
        color:'232323',
        marginTop:4
    },
    round:{
        marginLeft:-20,
        marginTop:10,
        flexDirection:'row',
        alignItems:'center',
    },
    review:{
        marginLeft:10,
        color:'#232323',
        fontFamily:'Montserrat-Regular',
        fontSize:13
    },
    image:{
        borderWidth:1,
        width:20,
        height:20,
        alignItems:'center',
        justifyContent:'center',
        borderRadius:10,marginTop:5,
        borderColor:'#dae1ed'
    },
    addCont:{
        borderWidth:1,
        borderColor:'#ED1717',
        flexDirection:'row',
        justifyContent:'space-between',
        width:'70%',
        paddingVertical:5,
        borderRadius:5,
        backgroundColor:'#fff'
    },
    add:{
        fontFamily:'Montserrat-SemiBold',
        fontSize:12,
        color:'#ED1717',
        marginLeft:30
    },
    plus:{
        fontFamily:'Montserrat-SemiBold',
        fontSize:15,
        color:'#ED1717',
        marginTop:-6,
        marginRight:4
    }

})